language: objective-c

matrix:
  include:
    - os: osx
      osx_image: xcode10.3
    - os: osx
      osx_image: xcode10.2
    - os: osx
      osx_image: xcode10.1

before_install:
  - gem install xcov --no-rdoc --no-ri --no-document --quiet
  - gem install slather --no-rdoc --no-ri --no-document --quiet
script:
  - xcodebuild -project KKBOXOpenAPI/KKBOXOpenAPI.xcodeproj -scheme KKBOXOpenAPI
  - xcodebuild -project KKBOXOpenAPI/KKBOXOpenAPI.xcodeproj -scheme KKBOXOpenAPITests -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1' test
after_success:
  - xcov --project KKBOXOpenAPI/KKBOXOpenAPI.xcodeproj --scheme KKBOXOpenAPITests
  - slather
