language: objective-c

matrix:
  include:
    - os: osx
      osx_image: xcode10.1

before_install:
  - gem install xcov
  - gem install slather
script:
  - xcodebuild -project KKBOXOpenAPI/KKBOXOpenAPI.xcodeproj -scheme KKBOXOpenAPI
  - xcodebuild -project KKBOXOpenAPI/KKBOXOpenAPI.xcodeproj -scheme KKBOXOpenAPITests -destination 'platform=iOS Simulator,name=iPhone XS,OS=12.1' test
after_success:
  - xcov --project KKBOXOpenAPI/KKBOXOpenAPI.xcodeproj --scheme KKBOXOpenAPITests
  - slather
